# Generated by Django 3.2.6 on 2021-08-31 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0007_alter_bookmark_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='tag',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
