# Generated by Django 3.2.6 on 2021-08-31 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0008_alter_bookmark_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='id',
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
