# Generated by Django 3.2.6 on 2021-08-31 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0010_alter_bookmark_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='tag',
        ),
    ]
