# Generated by Django 3.2.6 on 2021-08-31 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0011_remove_bookmark_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='tag',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='tags.tag'),
            preserve_default=False,
        ),
    ]
